######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 24 15:06:51 2010
######################################################################

TEMPLATE = app
TARGET = ../bin/tests
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += KMapperTest.h \
           ../src/DataBackend.h \
           ../src/KMapWidget.h \
           ../src/TruthTableWidget.h \
           ../src/EquationParser.h
SOURCES += KMapperTest.cc \
           tester.cc \
           ../src/DataBackend.cc \
           ../src/KMapWidget.cc \
           ../src/TruthTableWidget.cc \
           ../src/EquationParser.cc
LIBS += -lcppunit
