bank.cc File Reference
Client test program to test the account class hierarchy.
#include <iostream>
#include <string>
#include <vector>
#include <cctype>
#include `account.h`
#include `savingsAccount.h`
#include `chequingAccount.h`
#include `chequingSavingsAccount.h`
#include `myio.h`
Functions
void fill (vector< Account * > &)
fill the list of accounts by reading data from a file
void withdraw (const vector< Account * > &) throw (account_not_found)
withdraw money from an account
void deposit (const vector< Account * > &) throw (account_not_found)
deposit money to an account
void update (const vector< Account * > &)
perform end of month updates on all accounts
void print (const vector< Account * > &list)
Polymorphically print each account in the list.
void clear (vector< Account * > &list)
Remove all items from the list.
int find (const vector< Account * > &accts, const string &number)
find the index of the account which has this account number
void printMenu ()
print a list of available options.
void menuSelect (vector< Account * > &accts) throw (invalid_menu_choice)
select from the list provided by printMenu()
int main ()
the main function for the testing program
Detailed Description
It reads various types of accounts into a list from a file and allows you to print the entire list of accounts, deposit money to an account, withdraw money from an account and perform end of month updates. All these operations are done polymorphically.
Author: Jacob Pledger (using Rex's solution)
Date: Nov 6, 2009
Function Documentation
void clear (vector< Account * > & list)
Parameters:
$\leftrightarrow$ list imports the list to be cleared and exports the emptied list
Postcondition: the list will be empty i.e. list.size() = 0
Referenced by fill(), and main().
void deposit (const vector< Account * > & accounts) throw (account_not_found)
Parameters:
$\leftarrow$ accounts imports the list of accounts
Postcondition: the balance will be increased
Exceptions:
thrown if find() fails to locate an account
References find().
Referenced by menuSelect().
void fill (vector< Account * > & accounts)
Parameters:
$\rightarrow$ accounts exports the list of accounts
Precondition: the list is empty
References clear(), and openIn().
Referenced by main().
int find (const vector< Account * > & accounts, const string & number)
Parameters:
$\leftarrow$ accounts imports the list of accounts
$\leftarrow$ number imports the account number to search for
Returns: the index of the account number, -1 if not found
Referenced by deposit(), and withdraw().
void menuSelect (vector< Account * > & accts) throw (invalid_menu_choice)
Parameters:
$\leftarrow$ loaded vector of accounts
Precondition: the vector has been loaded with accounts
Exceptions:
thrown if the user enters an invalid choice
References clrStream(), deposit(), print(), printMenu(), update(), and withdraw().
Referenced by main().
void print (const vector< Account * > & accounts)
Parameters:
$\leftarrow$ accounts imports the list of accounts to print
Referenced by menuSelect().
void update (const vector< Account * > & accounts)
Parameters:
$\leftarrow$ accounts imports the list of accounts
Referenced by menuSelect().
void withdraw (const vector< Account * > & accounts) throw (account_not_found)
Parameters:
$\leftarrow$ accounts imports the list of accounts
Postcondition: the balance will be decreased
Exceptions:
thrown if find() fails to loacte a valid account
References find().
Referenced by menuSelect().