ChequingSavingsAccount Class Reference
A concrete derived class to represent a ChequingSavingsAccount.
#include <chequingSavingsAccount.h>
Public Member Functions
ChequingSavingsAccount (double rate=0.0, int numFree=0, int howMany=0, int fee=0)
default constructor
virtual istream & read (istream &is) throw (input_format_error)
Reads all information for a chequing savings account, from a stream.
virtual ostream & write (ostream &os) const
Writes all information for a chequing savings account, to a stream.
virtual void updateMonthEnd ()
Performs updates to the account at the end of the month.
Constructor & Destructor Documentation
ChequingSavingsAccount::ChequingSavingsAccount (double rate = 0.0, int numFree = 0, int howMany = 0, int fee = 0) [inline]
Parameters:
rate imports the monthly interest rate as a percentage
numFree imports the number of free withdrawals allowed
howMany imports the number of withdrawals made
fee imports the fee to be charged for a withdrawal
Member Function Documentation
istream & ChequingSavingsAccount::read (istream & is) throw (input_format_error) [virtual]
Parameters:
$\leftrightarrow$ is the stream to read from and the updated stream
Exceptions:
thrown by account::read() if incorrect
Returns: the updated stream, so that it can be cascaded
Reimplemented from ChequingAccount.
References Account::read(), ChequingAccount::readExtra(), and SavingsAccount::readExtra().
ostream & ChequingSavingsAccount::write (ostream & os) const [virtual]
Parameters:
$\leftrightarrow$ os the stream to write to and the updated stream
Returns: the updated stream, so that it can be cascaded
Reimplemented from ChequingAccount.
References Account::write(), ChequingAccount::writeExtra(), and SavingsAccount::writeExtra().
void ChequingSavingsAccount::updateMonthEnd () [virtual]
Postcondition: Interest earned has been added to the balance
The number of withdrawals is reset to 0
Reimplemented from ChequingAccount.
References ChequingAccount::updateMonthEnd(), and SavingsAccount::updateMonthEnd().
The documentation for this class was generated from the following files:
chequingSavingsAccount.h
chequingSavingsAccount.cc