ChequingAccount Class Reference
A simple abstract base class to represent a ChequingAccount.
#include <chequingAccount.h>
Public Member Functions
ChequingAccount (int numFree=0, int howMany=0, int fee=0)
default constructor
virtual istream & read (istream &is) throw (input_format_error)
Reads all information for a chequing account, from a stream.
virtual ostream & write (ostream &os) const
Writes all information for a chequing account, to a stream.
virtual void withdraw (int amount) throw (insufficient_funds)
Withdraws amount from this account.
virtual void updateMonthEnd ()
Performs updates to the account at the end of the month.
Protected Member Functions
virtual istream & readExtra (istream &is)
Reads the information,specific to a chequing account, from a stream.
virtual ostream & writeExtra (ostream &os) const
Writes the information, specific to a chequing account, to a stream.
Constructor & Destructor Documentation
ChequingAccount::ChequingAccount (int numFree = 0, int howMany = 0, int fee = 0) [inline]
Parameters:
numFree imports the number of free withdrawals allowed
howMany imports the number of withdrawals made
fee imports the fee to be charged for a withdrawal
Member Function Documentation
istream & ChequingAccount::read (istream & is) throw (input_format_error) [virtual]
Parameters:
$\leftrightarrow$ is the stream to read from and the updated stream
Exceptions:
thrown from account::read()
Returns: the updated stream, so that it can be cascaded
Reimplemented from Account.
Reimplemented in ChequingSavingsAccount.
References Account::read().
ostream & ChequingAccount::write (ostream & os) const [virtual]
Parameters:
$\leftrightarrow$ os the stream to write to and the updated stream
Returns: the updated stream, so that it can be cascaded
Reimplemented from Account.
Reimplemented in ChequingSavingsAccount.
References Account::write(), and writeExtra().
void ChequingAccount::withdraw (int amount) throw (insufficient_funds) [virtual]
Parameters:
$\leftarrow$ amount imports the amount to be withdrawn
Exceptions:
thrown if the balance is less than the desired amount
Postcondition: the balance has been increased by amount plus any service charges
Reimplemented from Account.
References Account::balance.
void ChequingAccount::updateMonthEnd () [virtual]
Postcondition: the number of withdrawals has been set to 0
Implements Account.
Reimplemented in ChequingSavingsAccount.
Referenced by ChequingSavingsAccount::updateMonthEnd().
istream & ChequingAccount::readExtra (istream & is) [protected, virtual]
Parameters:
$\leftrightarrow$ is the stream to read from and the updated stream
Returns: the updated stream, so that it can be cascaded
Referenced by ChequingSavingsAccount::read().
ostream & ChequingAccount::writeExtra (ostream & os) const [protected, virtual]
Parameters:
$\leftrightarrow$ os the stream to write to and the updated stream
Returns: the updated stream, so that it can be cascaded
Referenced by ChequingSavingsAccount::write(), and write().
The documentation for this class was generated from the following files:
chequingAccount.h
chequingAccount.cc