SavingsAccount Class Reference
A simple abstract base class to represent a SavingsAccount.
#include <savingsAccount.h>
Public Member Functions
SavingsAccount (double rate=0.0)
default constructor
virtual istream & read (istream &is) throw (input_format_error)
Reads all information for a savings account, from a stream.
virtual ostream & write (ostream &os) const
Writes all information for a savings account, to a stream.
virtual void updateMonthEnd ()
Performs updates to the account at the end of the month.
Protected Member Functions
virtual istream & readExtra (istream &is)
Reads the information,specific to savings account, from a stream.
virtual ostream & writeExtra (ostream &os) const
Writes the information, specific to a savings account, to a stream.
Protected Attributes
double interestRate
The monthly interest rate as a percentage.
Constructor & Destructor Documentation
SavingsAccount::SavingsAccount (double rate = 0.0) [inline]
Create a savings account with the specified interest rate
Parameters:
rate imports the monthly interest rate as a percentage
Member Function Documentation
istream & SavingsAccount::read (istream & is) throw (input_format_error) [virtual]
Parameters:
$\leftrightarrow$ is the stream to read from and the updated stream
Exceptions:
thrown when the input cannot be correctly interpreted
Returns: the updated stream, so that it can be cascaded
Reimplemented from Account.
Reimplemented in ChequingSavingsAccount.
References Account::read().
ostream & SavingsAccount::write (ostream & os) const [virtual]
Parameters:
$\leftrightarrow$ os the stream to write to and the updated stream
Returns: the updated stream, so that it can be cascaded
Reimplemented from Account.
Reimplemented in ChequingSavingsAccount.
References Account::write(), and writeExtra().
void SavingsAccount::updateMonthEnd () [virtual]
This function will calculate and add the interest earned to the balance at the end of the month.
Postcondition: the balance is increased by the amount of interest earned
Implements Account.
Reimplemented in ChequingSavingsAccount.
References Account::balance, and interestRate.
Referenced by ChequingSavingsAccount::updateMonthEnd().
istream & SavingsAccount::readExtra (istream & is) [protected, virtual]
Parameters:
$\leftrightarrow$ is the stream to read from and the updated stream
Returns: the updated stream, so that it can be cascaded
References interestRate.
Referenced by ChequingSavingsAccount::read().
ostream & SavingsAccount::writeExtra (ostream & os) const [protected, virtual]
Parameters:
$\leftrightarrow$ os the stream to write to and the updated stream
Returns: the updated stream, so that it can be cascaded
References interestRate.
Referenced by write(), and ChequingSavingsAccount::write().
The documentation for this class was generated from the following files:
savingsAccount.h
savingsAccount.cc