Account Class Reference
A simple abstract base class to represent an Account.
#include <account.h>
Public Member Functions
Account ()
default constructor
Account (const Account &)
copy constructor
virtual ~Account ()
Destructor; virtual so that sub class objects are correctly destroyed.
Account & operator= (const Account &)
Overload the assignment operator.
virtual istream & read (istream &is) throw (input_format_error)
Reads the information for an account from a stream.
virtual ostream & write (ostream &os) const
Writes the information for an account to a stream.
virtual void deposit (int amount)
Deposits amount into this account.
virtual void withdraw (int amount) throw (insufficient_funds)
Withdraws amount from this account.
virtual void updateMonthEnd ()=0
Performs updates to the account at the end of the month.
string getAccountNumber () const
Returns the account number.
Protected Attributes
int balance
The balance in this account.
Constructor & Destructor Documentation
Account::Account () [inline]
creates an account with a 0 balance and no customer
Account::Account (const Account & orig)
Parameters:
orig imports the Account to make a copy of
Account::~Account () [virtual]
clean up the Customer pointer
Postcondition: memory associated with the customer is returned to the heap
Member Function Documentation
istream & Account::read (istream & is) throw (input_format_error) [virtual]
Parameters:
$\leftrightarrow$ is the stream to read from and the updated stream
Exceptions:
thrown if the input does not start with a B or P or if the account number is of incorrect length
Returns: the updated stream, so that it can be cascaded
Reimplemented in ChequingAccount, ChequingSavingsAccount, and SavingsAccount.
References balance.
Referenced by operator>>(), SavingsAccount::read(), ChequingSavingsAccount::read(), and ChequingAccount::read().
ostream & Account::write (ostream & os) const [virtual]
Parameters:
$\leftrightarrow$ os the stream to write to and the updated stream
Returns: the updated stream, so that it can be cascaded
Parameters:
$\leftrightarrow$ os the stream to write to and the updated stream
Returns: the updated stream, so that it can be cascaded
Reimplemented in ChequingAccount, ChequingSavingsAccount, and SavingsAccount.
References balance.
Referenced by operator<<(), SavingsAccount::write(), ChequingSavingsAccount::write(), and ChequingAccount::write().
void Account::deposit (int amount) [virtual]
Parameters:
$\leftarrow$ amount imports the amount to be deposited
$\leftarrow$ amount imports the amount to be deposited
Postcondition: the balance has been increased by amount
References balance.
void Account::withdraw (int amount) throw (insufficient_funds) [virtual]
Parameters:
$\leftarrow$ amount imports the amount to be withdrawn
$\leftarrow$ amount imports the amount to be withdrawn
Exceptions:
thrown if the caller trys to withdraw more than available
Postcondition: the balance has been decreased by amount
Reimplemented in ChequingAccount.
References balance.
string Account::getAccountNumber () const
Returns: the account number
The documentation for this class was generated from the following files:
account.h
account.cc