myio.h File Reference
header file for a library of auxiliary IO functions
#include <string>
#include <fstream>
#include `errors.h`
Functions
void clrStream ()
Remove all data from the cin stream up to and including the next new line character.
char getResponse (char defalt)
Get a character from the cin stream.
void getValid (int &)
obtain a valid integer from the user
void getValid (double &)
obtain a valid real number from the user
void openIn (ifstream &iStr, string &filename) throw (invalid_file)
Attach a file to a stream.
void openOut (ofstream &oStr, string &filename) throw (invalid_file)
Attach a file to a stream.
Detailed Description
Author: Jacob Pledger (using Rex's Solution)
Date: Nov 6, 2009
Function Documentation
void clrStream ()
Postcondition: all data up to and including the next new line char is removed from cin
Referenced by getResponse(), getValid(), and menuSelect().
char getResponse (char defalt)
Parameters:
$\leftarrow$ defalt imports the default character to use if the enter key is pressed
Returns: defalt if the next character in the cin stream is a new line, otherwise returns the character entered
Postcondition: the cin stream is cleared
References clrStream().
void getValid (double & x)
Parameters:
$\rightarrow$ x exports the number obtained
Postcondition: x will be a valid real number
References clrStream().
void getValid (int & i)
Parameters:
$\rightarrow$ i exports the integer obtained
Postcondition: i will be a valid integer
References clrStream().
void openIn (ifstream & iStr, string & filename) throw (invalid_file)
Parameters:
$\rightarrow$ iStr exports the stream that the file was attached to
$\leftrightarrow$ filename imports the name of the file to be opened and exports the name of the file that was opened
Exceptions:
thrown if the user enters an unusable filename, or the program cannot open the file
Postcondition: iStr is attached to a valid file, ready for extraction
Referenced by fill().
void openOut (ofstream & oStr, string & filename) throw (invalid_file)
Parameters:
$\rightarrow$ oStr exports the stream that the file was attached to
$\leftrightarrow$ filename imports the name of the file to be opened and exports the name of the file that was opened
Exceptions:
thrown if the user enters an unusable filename, or the program cannot open the file
Postcondition: oStr is attached to a valid file, ready for insertion