/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SIMP_H_RPCGEN
#define _SIMP_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define foo 127
#define Pi 3.1415926

struct operands {
	int x;
	int y;
};
typedef struct operands operands;
#ifdef __cplusplus
extern "C" bool_t xdr_operands(XDR *, operands*);
#elif __STDC__
extern  bool_t xdr_operands(XDR *, operands*);
#else /* Old Style C */
bool_t xdr_operands();
#endif /* Old Style C */


struct result {
	int x;
	int y;
	int r;
};
typedef struct result result;
#ifdef __cplusplus
extern "C" bool_t xdr_result(XDR *, result*);
#elif __STDC__
extern  bool_t xdr_result(XDR *, result*);
#else /* Old Style C */
bool_t xdr_result();
#endif /* Old Style C */


#define SIMP_PROG ((rpc_uint)555555555)
#define SIMP_VERSION ((rpc_uint)1)

#ifdef __cplusplus
#define ADD ((rpc_uint)1)
extern "C" int * add_1(operands *, CLIENT *);
extern "C" int * add_1_svc(operands *, struct svc_req *);
#define SUB ((rpc_uint)2)
extern "C" int * sub_1(operands *, CLIENT *);
extern "C" int * sub_1_svc(operands *, struct svc_req *);
#define TWOADD ((rpc_uint)3)
extern "C" result * twoadd_1(operands *, CLIENT *);
extern "C" result * twoadd_1_svc(operands *, struct svc_req *);
#define TWOSUB ((rpc_uint)4)
extern "C" result * twosub_1(operands *, CLIENT *);
extern "C" result * twosub_1_svc(operands *, struct svc_req *);

#elif __STDC__
#define ADD ((rpc_uint)1)
extern  int * add_1(operands *, CLIENT *);
extern  int * add_1_svc(operands *, struct svc_req *);
#define SUB ((rpc_uint)2)
extern  int * sub_1(operands *, CLIENT *);
extern  int * sub_1_svc(operands *, struct svc_req *);
#define TWOADD ((rpc_uint)3)
extern  result * twoadd_1(operands *, CLIENT *);
extern  result * twoadd_1_svc(operands *, struct svc_req *);
#define TWOSUB ((rpc_uint)4)
extern  result * twosub_1(operands *, CLIENT *);
extern  result * twosub_1_svc(operands *, struct svc_req *);

#else /* Old Style C */
#define ADD ((rpc_uint)1)
extern  int * add_1();
extern  int * add_1_svc();
#define SUB ((rpc_uint)2)
extern  int * sub_1();
extern  int * sub_1_svc();
#define TWOADD ((rpc_uint)3)
extern  result * twoadd_1();
extern  result * twoadd_1_svc();
#define TWOSUB ((rpc_uint)4)
extern  result * twosub_1();
extern  result * twosub_1_svc();
#endif /* Old Style C */

#endif /* !_SIMP_H_RPCGEN */
